name: quadrapassel
adopt-info: quadrapassel
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22

layout:
  /usr/share/quadrapassel:
    bind: $SNAP/usr/share/quadrapassel

slots:
  # for GtkApplication registration
  quadrapassel:
    interface: dbus
    bus: session
    name: org.gnome.Quadrapassel

apps:
  quadrapassel:
    command: usr/bin/quadrapassel
    extensions: [gnome]
    plugs:
      - audio-playback
    desktop: usr/share/applications/org.gnome.Quadrapassel.desktop
    common-id: org.gnome.Quadrapassel.desktop
    environment:
      DISABLE_WAYLAND: 'true'

parts:
  quadrapassel:
# ext:updatesnap
    source: https://gitlab.gnome.org/GNOME/quadrapassel.git
    source-type: git
    source-tag: '40.2'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    parse-info: [usr/share/metainfo/org.gnome.Quadrapassel.appdata.xml]
    build-packages:
      - libmanette-0.2-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      sed -i.bak -e 's|symlink_media: true|symlink_media: false|g' $CRAFT_PART_SRC/help/meson.build
      craftctl default

  libraries:
    plugin: nil
    stage-packages:
      - libmanette-0.2-0
    prime:
      - usr/lib/*/libmanette*
